version: "3"
services:
  queue:
    image: redis:5.0.7
    ports:
      - 6379:6379
    volumes:
      - ./docker/queue/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    networks:
      - shared_network

  dashboard:
    build:
      context: .
      dockerfile: ./docker/dashboard/DockerFile
    ports:
      - 9181:9181
    command: rq-dashboard -H queue
    depends_on:
      - queue
    networks:
      - shared_network

  worker:
    depends_on:
      - queue
    build:
      context: .
      dockerfile: ./docker/worker/DockerFile
    env_file:
      - .env.worker
    volumes:
      - ./worker:/worker
    command: python /worker/manage.py run_worker
    networks:
      - shared_network

networks:
  shared_network:
    external: false  # when false we expect this project to create network
